"""add currencies table

Revision ID: 56e1cfc8b0a4
Revises: fa5122597c28
Create Date: 2022-06-08 21:09:02.149720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e1cfc8b0a4'
down_revision = 'fa5122597c28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=3), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies_price')),
    sa.UniqueConstraint('id', name=op.f('uq_currencies_price_id'))
    )
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_table('currencies_price')
    # ### end Alembic commands ###
